spring:
  datasource:
    url: jdbc:mysql://localhost:3307/uniclub_web
    username: root
    password: admin12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      max-file-size: 500KB
      max-request-size: 500KB
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

mydata:
  secretkey: DdBkCPYyuwsr4TuAikzGwHBGBQlsos1KDAJ6OwRUsww=

upload:
  file:
    path: D:\Workspace\Java\BootCamp004\uploads
redis:
  port: 6379
  host: localhost
logging:
  level:
    root: info
  file:
    name: ./log/dev.log

mailServer:
  host: smtp.gmail.com
  port: 587
  email: 12a1nguyenquocbao1412@gmail.com
  password: "ndpc raht qwwp tqhv"
  protocol: smtp
  isSSL: false
